version: '0.2'

services:

  backend:
    env_file:
      - .env
    build: ./services/backend
    ports:
      - 5001:5001
    volumes:
      - ./services/backend:/app
    command: uvicorn src.main_redis:app --reload --host 0.0.0.0 --port 5001

  frontend:
      build: ./services/frontend
      volumes:
        - './services/frontend:/app'
        - '/app/node_modules'
      ports:
        - 8000:8000

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning --requirepass $REDIS_PASSWORD
    volumes:
      - ./data:/data