version: '0.2'

services:

  backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./services/backend/Dockerfile
    ports:
      - 5001:5001
    volumes:
      - ./services/backend/src:/app
      - ./services/utils:/app/utils
    command: uvicorn main_redis:app --reload --host 0.0.0.0 --port 5001

  frontend:
      build: ./services/frontend
      volumes:
        - './services/frontend:/app'
        - '/app/node_modules'
      ports:
        - 8000:8000